#!/usr/bin/bash -xe

cluster_name=$1

trap "echo Failed > clusters/${cluster_name}/STATUS" EXIT

# Set status to Pending
echo Pending > clusters/${cluster_name}/STATUS

# We cannot provision multiple clusters at the same time,
# wait until all the others are done
while find clusters -type f -name STATUS | xargs grep "Reprovisioning"; do
    sleep 30
done

# Set status to Reprovisioning
echo Reprovisioning > clusters/${cluster_name}/STATUS

# Reprovision
(
    source clusters/${cluster_name}/config
    cd ~/dev-scripts
    make clean
    make
)

# Set status to Available
echo Available > clusters/${cluster_name}/STATUS

# Sleep until canceled
sleep infinity
