#!/usr/bin/bash -xe

cluster_name=$1

if tmux list-sessions | grep ${cluster_name}; then
    # Cancel whatever is running in there
    tmux send-keys -t ${cluster_name}.0 ^C

    # Clear previous logs if any
    tmux send-keys -t ${cluster_name}.0 "clear" ENTER
    tmux clear-history -t ${cluster_name}.0
else
    # Initialize a new session
    tmux set-option -g history-limit 100000 \; new-session -d -s ${cluster_name}
fi

# Reprovision the cluster
tmux send-keys -t ${cluster_name}.0 "./reprovision ${cluster_name}" ENTER
